title: Julie Steele
url: ""
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Home"
   link: ""
 - name: "What I'm Up To"
   link: "what-im-up-to"
 - name: "Challenges/ideas"
   link: "challenges-ideas"
 - name: "Feedback"
   link: "resume.pdf"
 - name: "Random"
   link: "random"
 - name: "Contact"
   link: "contact"
