title: Julie Steele
url: ""
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://github.com/ankitsultana"
footer_text: "Page design by Ankit Sultana"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Home"
   link: "/index"
 - name: "Thoughts" #or called entries 
   link: "/Thoughts"
 - name: "Goals & Challenges"
   link: "/goals-and-challenges"
 - name: "Feedback"
   link: "https://forms.gle/PqbsZTjuBC7EvfEr8"
 - name: "Reflection" 
   link: "/reflection"
 - name: "Careers"
   link: "/careers"
  


collections:
  Thoughts:
    output: true
    permalink: /:collection/:path/ # or any permalink style you prefer #what does this mean 

