title: Julie Steele
url: ""
baseurl: ""
favicon: favicon.ico
description: "Julie Steele's personal website"
markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "Home"
   link: "/"
 - name: "Thoughts" #or called entries 
   link: "/thoughts"
 - name: "Goals & Challenges"
   link: "/goals-and-challenges"
 - name: "Lists"
   link: "/lists"
 - name: "CV"
   link: resume.pdf
 - name: "Feedback"
   link: "https://forms.gle/PqbsZTjuBC7EvfEr8"
 - name: "Apply"
   link: "/apply"
  


collections:
  thoughts:
    output: true
    permalink: /:collection/:path/ # or any permalink style you prefer #what does this mean 
  lists:
    output: true
    permalink: /:collection/:path/ # or any permalink style you prefer #what does this mean 

